services:
  - type: web
    name: cloudocs-ui
    env: static
    staticPublishPath: ui/dist
    buildCommand: npm install && npm run build
    startCommand: serve ui/dist
    envVars:
      - key: NODE_VERSION
        value: 18

  - type: web
    name: cloudocs-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - fromDotEnv: true
